library(sqldf)
f = read.csv.sql("household_power_consumption.txt",sep=";",header = TRUE,
                 sql = "select * from file where Date = '1/2/2007' or Date = '2/2/2007' ")
f$Date <- as.Date(f$Date,format = "%d/%m/%Y")
f$Dt <- as.POSIXct(paste(f$Date, f$Time))
png("plot3.png", width=480, height=480, units="px")
plot(f$Sub_metering_1~f$Dt,type="l",xlab = "",ylab = "Energy sub metering")
lines(f$Sub_metering_2~f$Dt,col="red")
lines(f$Sub_metering_3~f$Dt,col="blue")
legend("topright",lty=1, lwd=2,,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"))
dev.off()